#!/usr/bin/env php
<?php
define("CURRENT_WORKING_DIR", str_replace("\\", "/", dirname(__FILE__)));

// foreach (explode("\n", trim(shell_exec('find '.CURRENT_WORKING_DIR.'/*/index.md'))) as $source) {
foreach (explode("\n", trim(shell_exec('find '.CURRENT_WORKING_DIR.'/ru/index.md'))) as $source) {
	// $html = preg_replace('~\.md$~', '.html', $source);
	$html = 'index_php.html';
	passthru('php '.CURRENT_WORKING_DIR.'/parser/parse.php'
		.' '.escapeshellarg($source)
		.' > '.escapeshellarg($html.'.tmp').'; mv -f '.escapeshellarg($html.'.tmp').' '.escapeshellarg($html));
}
