#!/usr/bin/env php
<?php

// хук для сервера

define("CURRENT_WORKING_DIR", str_replace("\\", "/", dirname(__FILE__)));

foreach (explode("\n", trim(shell_exec('find '.CURRENT_WORKING_DIR.'/*/index.md'))) as $source) {
	$html = preg_replace('~\.md$~', '.html', $source);
	passthru('python '.CURRENT_WORKING_DIR.'/backdoc.py'
		.' --source '.escapeshellarg($source)
		.' > '.escapeshellarg($html.'.tmp').'; mv -f '.escapeshellarg($html.'.tmp').' '.escapeshellarg($html));
}
